materiais_info = [
    {"nome": "Jornal", "tempo": "2 a 6 semanas", "tempo_anos": (0.04, 0.12), "descricao": "Biodegradável. Pode ser reciclado ou usado para compostagem."},
    {"nome": "Papel", "tempo": "3 a 6 meses", "tempo_anos": (0.25, 0.5), "descricao": "Reciclável. Deve ser descartado limpo e seco."},
    {"nome": "Embalagens de papel", "tempo": "1 a 4 meses", "tempo_anos": (0.08, 0.33), "descricao": "Recicláveis se não estiverem contaminadas com gordura."},
    {"nome": "Guardanapos de papel", "tempo": "3 meses", "tempo_anos": (0.25, 0.25), "descricao": "Não reciclável após o uso. Ideal para compostagem se limpo."},
    {"nome": "Pano", "tempo": "6 meses a 1 ano", "tempo_anos": (0.5, 1), "descricao": "Pode ser reutilizado ou destinado à coleta de resíduos têxteis."},
    {"nome": "Filtro de cigarro", "tempo": "Mais de 5 anos", "tempo_anos": (5, 10), "descricao": "Altamente poluente. Contém resíduos tóxicos."},
    {"nome": "Palito de fósforo", "tempo": "2 anos", "tempo_anos": (2, 2), "descricao": "Biodegradável, mas pode ser descartado como lixo comum."},
    {"nome": "Madeira pintada", "tempo": "Mais de 13 anos", "tempo_anos": (13,  20), "descricao": "Pode liberar produtos tóxicos. Não deve ser queimada."},
    {"nome": "Náilon", "tempo": "Mais de 20 anos", "tempo_anos": (20, 40), "descricao": "Não biodegradável. Deve ser reciclado em pontos específicos."},
    {"nome": "Metal", "tempo": "Mais de 100 anos", "tempo_anos": (100, 600), "descricao": "Altamente reciclável. Economiza recursos naturais."},
    {"nome": "Alumínio", "tempo": "Mais de 200 anos", "tempo_anos": (200, 500), "descricao": "Totalmente reciclável. Evite o descarte no lixo comum."},
    {"nome": "Plástico", "tempo": "Mais de 400 anos", "tempo_anos": (400, 1000), "descricao": "Não biodegradável. Polui solos e oceanos. Reciclagem é essencial."},
    {"nome": "Vidro", "tempo": "Mais de 1000 anos", "tempo_anos": (1000, 9999999999), "descricao": "Reciclável infinitamente. Perigoso se quebrado."},
    {"nome": "Borracha e Pneu", "tempo": "Tempo indeterminado", "tempo_anos": (9999999999, 9999999999), "descricao": "Deve ser descartado em pontos de coleta específicos. Altamente poluente."},
    {"nome": "Chiclete", "tempo": "5 anos", "tempo_anos": (4, 5), "descricao": "Não biodegradável. Prejudica vias públicas e ambientes naturais."},
    {"nome": "Cascas de frutas", "tempo": "3 meses", "tempo_anos": (0.20, 0.25), "descricao": "Orgânico. Ideal para compostagem."},
    {"nome": "Copinhos de plástico", "tempo": "200 a 450 anos", "tempo_anos": (200, 450), "descricao": "Descartável, mas reciclável. Substitua por copos reutilizáveis."},
    {"nome": "Latas de alumínio", "tempo": "100 a 500 anos", "tempo_anos": (100, 500), "descricao": "Reciclável. Um dos materiais mais reciclados do mundo."},
    {"nome": "Tampinhas de garrafa", "tempo": "100 a 500 anos", "tempo_anos": (100, 500), "descricao": "Recicláveis. Pode acumular água parada e gerar focos de dengue."},
    {"nome": "Pilhas e baterias", "tempo": "100 a 500 anos", "tempo_anos": (100, 500), "descricao": "Contêm metais pesados. Devem ser descartadas em pontos de coleta específicos."},
    {"nome": "Fralda descartável", "tempo": "450 a 600 anos", "tempo_anos": (450, 600), "descricao": "Altamente poluente. Deve ser descartada corretamente. Evite o uso excessivo."}
]
